<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
    <UserSecretsId>e06dae00-410e-4d69-b3fe-9451234a4103</UserSecretsId>
  </PropertyGroup>

</Project>
